# Remove `inherit_from: .rubocop_todo.yml` if `.rubocop_todo.yml` is empty.
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  EnabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - "Gemfile"
    - "vendor/**/*"

# Allow non ASCII comment.
Style/AsciiComments:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Copyright:
  Enabled: false

# rubocop-performance
Performance:
  Exclude:
    - "**/test/**/*"
    - "**/spec/**/*"
