version: "3.8"

services:
  ruby_project_development:
    image: ruby_project_development
    container_name: ruby_project_development
    build:
      context: ./docker/development
      dockerfile: Dockerfile
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
    env_file: ./docker/development/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
