version: "3"

services:
  ruby_project_development:
    image: ruby_project_development
    container_name: ruby_project_development
    build:
      context: ./docker/development
      dockerfile: Dockerfile
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/:cached
    env_file: ./docker/development/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: json-file
      options:
        max-file: 3
        max-size: 1m
